blank_issues_enabled: false
contact_links:
  - name: "💬 Thảo luận & Hỏi đáp"
    url: "https://t.me/kyicchat" 
    url: "https://discord.gg/qUXBQFYa"
    # Link nhóm Telegram/Discord của anh
    about: "Nếu bạn muốn hỏi đáp, giao lưu hoặc yêu cầu thêm tweak, hãy thảo luận tại đây."