name: "Clean All Workflow Runs"

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: "Delete all workflow runs"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Lấy danh sách ID của tất cả các workflow
          workflow_ids=$(gh api repos/${{ github.repository }}/workflows --jq '.workflows[].id')
          
          for id in $workflow_ids; do
            echo "Đang dọn dẹp Workflow ID: $id"
            # Xóa tất cả các lần chạy của từng workflow
            gh run delete --workflow $id --all || echo "Workflow $id đã sạch."
          done
